version: "3.3"
services:
  jupyterlab:
    build: .
    container_name: docker-jupyterlab
    # ホスト内のworkディレクトリとコンテナ内の/home/jovyan/workディレクトリを紐付けさせる
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - '8888:8888'